/* Generated By:JavaCC: Do not edit this line. BwyGrammarTreeConstants.java Version 5.0 */
package dd;

public interface BwyGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTATEMENTBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTLOOPSTATEMENT = 4;
  public int JJTBOOLSTATEMENT = 5;
  public int JJTBOOLANDEXPRESSION = 6;
  public int JJTCONSTATEMENT = 7;
  public int JJTCONEXPRESSION = 8;
  public int JJTSEQSTATEMENT = 9;
  public int JJTDECSTATEMENT = 10;
  public int JJTASSSTATEMENT = 11;
  public int JJTIDENTIFIER_DEC = 12;
  public int JJTIDENTIFIER_ASS = 13;
  public int JJTTYPE = 14;
  public int JJTEXPRESSION = 15;
  public int JJTADDITIVEEXPRESSION = 16;
  public int JJTMULTIPLICATIVEEXPRESSION = 17;
  public int JJTUNARYEXPRESSION = 18;
  public int JJTIDENTIFIER = 19;
  public int JJTINTEGER = 20;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "StatementBlock",
    "statement",
    "loopStatement",
    "BoolStatement",
    "BoolAndExpression",
    "conStatement",
    "ConExpression",
    "seqStatement",
    "decStatement",
    "assStatement",
    "Identifier_dec",
    "Identifier_ass",
    "type",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=d017f1991e95db370555f6f076c46d3f (do not edit this line) */
